version: '3'
# Using a blue/green deployment strategy to avoid downtime and ensure a smooth transition + rollbacks
# These env variable will be configured in the github actions workflow
# and will be passed to the docker container at runtime
services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${DOCKER_IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${NEW_PORT}:3001" 
    env_file:
    - path: /home/ubuntu/.env
      required: true 
